version: '3.8'

services:
  ms-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: lde.ms-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MSSQLServerStrongPassword123!"
    hostname: localhost
    ports:
      - "1433:1433"
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 8002:5432
  
  challenge-catalog.api:
    container_name: lde.challenge-catalog.api
    build:
      context: .
      dockerfile: ./Services/ChallengeCatalog/ChallengeCatalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4001
      - ConnectionString=server=host.docker.internal;port=8002;database=DonateChallenger.Services.ChallengeCatalogDb;uid=postgres;password=postgres;
      - PathBase=http://donate-challenger.com:4001
    depends_on:
      - postgres
    command: dotnet run
    ports:
      - 4001:4001
  
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.2