version: '3.8'

services:
  ms-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: lde.ms-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MSSQLServerStrongPassword123!"
    hostname: localhost
    ports:
      - "1433:1433"
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 8002:5432
  
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  
  redis:
    image: redis
    container_name: lde.redis
    ports:
      - "6380:6379"

  challenge-catalog.api:
    container_name: lde.challenge-catalog.api
    build:
      context: .
      dockerfile: ./Services/ChallengeCatalog/ChallengeCatalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4001
      - ConnectionString=server=host.docker.internal;port=8002;database=DonateChallenger.Services.ChallengeCatalogDb;uid=postgres;password=postgres;
      - PathBase=http://donate-challenger.com:4001
      - Authorization__Authority=http://donate-challenger.com:4000
    depends_on:
      - postgres
    command: dotnet run
    ports:
      - 4001:4001
  
  payment.api:
    container_name: lde.payment.api
    build:
      context: .
      dockerfile: ./Services/Payment/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4003
      - PathBase=http://donate-challenger.com:4003
      - Authorization__Authority=http://donate-challenger.com:4000
    command: dotnet run
    ports:
      - 4003:4003
        
  challenges-storage.api:
    container_name: lde.challenges-storage.api
    build:
      context: .
      dockerfile: ./Services/ChallengesTemporaryStorage/ChallengesTemporaryStorage.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4004
      - PathBase=http://donate-challenger.com:4004
      - Authorization__Authority=http://donate-challenger.com:4000
    command: dotnet run
    depends_on:
      - redis
    ports:
      - 4004:4004
  
  identity.api:
    container_name: lde.identity.api
    build:
      context: .
      dockerfile: ./Services/Identity/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4000
      - AppDbConnection=server=host.docker.internal;database=DonateChallenger.Services.IdentityDb.Identity;User ID=sa;Password=MSSQLServerStrongPassword123!;
      - ConfigurationDbConnection=server=host.docker.internal;database=DonateChallenger.Services.IdentityDb.Configuration;User ID=sa;Password=MSSQLServerStrongPassword123!;
      - PersistedGrantDbConnection=server=host.docker.internal;database=DonateChallenger.Services.IdentityDb.PersistedGrant;User ID=sa;Password=MSSQLServerStrongPassword123!;
      - PathBase=http://donate-challenger.com:4000
    depends_on:
      - ms-sql-server
    ports:
      - 4000:4000
  
  web.react-client:
    container_name: lde.web.react-client
    build:
      context: ./Web/react-client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - challenge-catalog.api
      - identity.api

  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.2