import { Container } from "inversify";
import DefaultChallengeCatalogService, { ChallengeCatalogService } from "../../services/ChallengeCatalogService";
import DefaultHttpService, { HttpService } from "../../services/HttpService";
import AuthStore from "../../oidc/AuthStore";
import ChallengesStore from "../../stores/components/ChallengesStore";
import ChallengeStore from "../../stores/components/ChallengeStore";
import iocServices from "./iocServices";
import iocStores from "./iocStores";
import DefaultAuthenticationService, { AuthenticationService } from "../../oidc/AuthenticationService";
import DefaultLocalStorageService, { LocalStorageService } from "../../services/LocalStorageService";
import ChallengesBoardStore from "../../stores/components/ChallengesBoardStore";
import UserRoleStore from "../../stores/UserRoleStore";
import DefaultStreamerService, { StreamerService } from "../../services/StreamerService";
import StreamerProfileStore from "../../stores/components/StreamerProfileStore";
import DonaterStore from "../../stores/DonaterStore";
import StreamersStore from "../../stores/components/StreamersStore";
import ChallengeOrderStore from "../../stores/components/ChallengeOrderStore";

export const container = new Container();
container.bind<HttpService>(iocServices.httpService).to(DefaultHttpService).inSingletonScope();
container.bind<ChallengeCatalogService>(iocServices.challengeCatalogService).to(DefaultChallengeCatalogService).inTransientScope();
container.bind<AuthenticationService>(iocServices.authenticationService).to(DefaultAuthenticationService).inSingletonScope();
container.bind<LocalStorageService>(iocServices.localStorageService).to(DefaultLocalStorageService).inTransientScope();
container.bind<StreamerService>(iocServices.streamerService).to(DefaultStreamerService).inTransientScope();

container.bind<ChallengesStore>(iocStores.challengesStore).to(ChallengesStore).inSingletonScope();
container.bind<ChallengeStore>(iocStores.challengeStore).to(ChallengeStore).inSingletonScope();
container.bind<ChallengesBoardStore>(iocStores.challengesBoardStore).to(ChallengesBoardStore).inSingletonScope();
container.bind<AuthStore>(iocStores.authStore).to(AuthStore).inSingletonScope();
container.bind<UserRoleStore>(iocStores.userRoleStore).to(UserRoleStore).inTransientScope();
container.bind<StreamerProfileStore>(iocStores.streamerProfileStore).to(StreamerProfileStore).inSingletonScope();
container.bind<DonaterStore>(iocStores.donaterStore).to(DonaterStore).inTransientScope();
container.bind<StreamersStore>(iocStores.streamersStore).to(StreamersStore).inSingletonScope();
container.bind<ChallengeOrderStore>(iocStores.challengeOrderStore).to(ChallengeOrderStore).inSingletonScope();