export default {
     challengesStore: Symbol("challengesStore"), 
     challengeStore: Symbol("challengeStore"),
     authStore: Symbol("authStore"),
     userRoleStore: Symbol("userRoleStore"),
     streamerProfileStore: Symbol("streamerProfileStore"),
     donaterStore: Symbol("donaterStore"),
     streamersStore: Symbol("streamersStore"),
     challengeOrderStore: Symbol("challengeOrderStore"),
     challengesTempStorageStore: Symbol("challengesTempStorageStore"),
     challengesBoardPaginationStore: Symbol("challengesBoardPaginationStore"),
     challengesBoardFiltersStore: Symbol("challengesBoardFiltersStore"),
     challengesBoardStore: Symbol("challengesBoardStore"),
     challengeForAddingStore: Symbol("challengeForAddingStore"),
     commentPaginationStore: Symbol("commentPaginationStore"),
     commentsStore: Symbol("commentsStore"),
     dateTimeStore: Symbol("dateTimeStore"),
     userProfileStore: Symbol("userProfileStore"),
     commentsBlockStore: Symbol("commentsBlockStore"),
     commentStore: Symbol("commentStore"),
}